# Prepares, builds and publishes new releases

name: Release

# On changes to release branches
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: 🙌 Prepare release
        id: release-please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          command: manifest
          config-file: .github/release-please.json
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
      releases: ${{ toJson(steps.release-please.outputs) }}

  publish:
    name: Publish

    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releases_created }}

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.release.outputs.paths_released) }}

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: 📢 Publish new release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.path == '.' && ':publish' || format('{0}:publish', matrix.path) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          CURSEFORGE_DEBUG: ${{ secrets.CURSEFORGE_DEBUG }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_DEBUG: ${{ secrets.MODRINTH_DEBUG }}

      - name: 📦 Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ fromJson(needs.release.outputs.releases)[matrix.path == '.' && 'tag_name' || format('{0}--tag_name', matrix.path)] }}
          files: ${{ matrix.path }}/**/build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}
